TOOLS_DIR := /opt/docbook/tools

# XML_SRCDIR defines the place where XMLs present.
XML_SRCDIR := .

# XML_INDEX_NAME defines the main XML index page without extension.
XML_INDEX_NAME := index

# MM_SRC is FreeMind .mm filename
MM_SRC := whodo_howto.mm

build_all: index.xml all

index.xml: index.template $(TOOLS_DIR)/bin/update-docs.pl
	perl $(TOOLS_DIR)/bin/update-docs.pl --template=$< --xml=$@ --dir=..
